# Generated by Django 5.1.6 on 2025-02-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Full Name"
            ),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="is_superuser",
            field=models.BooleanField(default=False, verbose_name="Superuser"),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="username",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Username"
            ),
        ),
    ]
